wandb_version: 1

epsilon:
  desc: null
  value: 0.1
alpha:
  desc: null
  value: 0.99
lossval:
  desc: null
  value: -1
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.16.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706935595.991528
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      - 23
      4: 3.10.10
      5: 0.16.1
      8:
      - 4
      - 5
      13: darwin-arm64
